# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'artist_form_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Artist_add(object):
    def setupUi(self, Artist_add):
        Artist_add.setObjectName("Artist_add")
        Artist_add.resize(340, 200)
        self.layoutWidget = QtWidgets.QWidget(Artist_add)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 281, 145))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        self.label2.setObjectName("label2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.lineEdit2_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit2_name.setObjectName("lineEdit2_name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit2_name)
        self.label3 = QtWidgets.QLabel(self.layoutWidget)
        self.label3.setObjectName("label3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.lineEdit3_description = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit3_description.setObjectName("lineEdit3_description")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit3_description)
        self.button1_Submit = QtWidgets.QPushButton(self.layoutWidget)
        self.button1_Submit.setObjectName("button1_Submit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.button1_Submit)
        self.lineEdit1_artistID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit1_artistID.setObjectName("lineEdit1_artistID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit1_artistID)
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        self.label1.setObjectName("label1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)

        self.retranslateUi(Artist_add)
        QtCore.QMetaObject.connectSlotsByName(Artist_add)

    def retranslateUi(self, Artist_add):
        _translate = QtCore.QCoreApplication.translate
        Artist_add.setWindowTitle(_translate("Artist_add", "Add Artist"))
        self.label2.setText(_translate("Artist_add", "Name"))
        self.lineEdit2_name.setPlaceholderText(_translate("Artist_add", "XYZ"))
        self.label3.setText(_translate("Artist_add", "Description"))
        self.lineEdit3_description.setPlaceholderText(_translate("Artist_add", "About the Artist"))
        self.button1_Submit.setText(_translate("Artist_add", "&Submit"))
        self.lineEdit1_artistID.setPlaceholderText(_translate("Artist_add", "1234"))
        self.label1.setText(_translate("Artist_add", "Artist ID"))
